<html>
<head>
<style>
h2{
	text-align:center;
}
</style>
</head>
<body>

<center><img src="http://quadrobay.co.in/eduapps_api/eduapps/ilplogo.png" style="width: 10%;"></center>
<h2>India Literacy Project</h2>
<h2>A catalyst for 100% literacy in India</h2>
<h4>India Literacy Project (ILP) is a developmental support organization that works in partnership with local Non-Governmental Organizations (NGOs) and networks in India to play the role of a catalyst for literacy.</h4>
<h4>ILP does not warrant the accuracy or completeness of the materials or the reliability of any advices, opinions, statements or other information as displayed or distributed through the Applications or Website herein after referred to as Applications. You acknowledge that any reliance on any such opinion, advice, statement, memorandum, or information shall be at your own/sole risk and consequences attached there to.\n \n ILP as being a developer to the Applications reserves its right, in its sole discretion, to correct/rectify any errors or omissions in any portion of the materials.</h4>
</body>
</html>