<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Pilot API</title>
<script src="<?php echo $this->baseUrl()?>/js/jquery.min.js"></script>
    <link href="<?php echo $this->baseUrl()?>/css/bootstrap.min.css" rel="stylesheet">
	<script src="<?php echo $this->baseUrl()?>/js/main.js" type="text/javascript"></script>
    <link rel="stylesheet" href="<?php echo $this->baseUrl()?>/css/main.css">
<script src="<?php echo $this->baseUrl()?>/js/Response.js"></script>
<script src="<?php echo $this->baseUrl()?>/js/StatusCode.js"></script>
<script type="text/javascript">
var SERVER_URL="<?php echo SERVER_URL;?>";var SERVER_VIDEO_URL="<?php echo SERVER_VIDEO_URL;?>";
</script>
</head>
<body>
<div class="container">
	<?php echo $this->layout()->content; ?>
</div>
</body>
</html>